name: "Deployment Taxi Application"

on:
  push:
    branches: [ "main" ]
  
env:
  PROJECT_PATH: TaxiApplication/TaxiApplication.csproj
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
  
      - uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 8.0

      - run: dotnet restore ${{ env.PROJECT_PATH }}
  
      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
  
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64
